# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe25e61800639d306cfaf33830635db1c108193d678eb009b05bfd88c2d3d04190032e1866e5a87957d7dfe027a52c204b0434ec4ba81c49b2d495d7a9361905

test:
  secret_key_base: 01352a2cf40b63c9cb03e0b15f1b648a9031ffcf135139ac59b834ef2c61eccb7038412c1e914b5060600e7f4dd646b65fb8383e08065ec7c86cd5cfb9a2f637

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
